# Generated by Django 5.2.5 on 2025-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minaturn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
