# Generated by Django 5.2.5 on 2025-08-17 20:57

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minaturn', '0002_queueentry_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890', length=6, max_length=6, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890', length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
