# Generated by Django 5.2.5 on 2025-08-17 21:00

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minaturn', '0003_alter_queue_id_alter_queueentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='LGXHFKPDS1234567890', length=6, max_length=6, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ADFPHSMR1234567890', length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
