# Generated by Django 5.2.5 on 2025-08-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minaturn', '0004_alter_queue_id_alter_queueentry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('served', 'Served')], default='waiting', max_length=20),
        ),
    ]
