# Generated by Django 5.2.5 on 2025-08-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minaturn', '0005_queueentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
